<div class="card">
    <h2><?= $user->getName(); ?></h2>
    <form method="post" action="/user/changeavatar" enctype="multipart/form-data" class="avatar-form">
        <label for="ava"><img src="<?= $user->getAva() ?? "/images/no_image.jpg" ?>" width="200" /></label>
        <input type="file" id="ava" name="ava"   accept=".jpg, .jpeg, .png" /><br />
        <input type="submit" value="Загрузить аву" />
    </form>
    <!--<div class="fakeimg" style="height:100px;">Avatar</div>-->
    <p>Ваш ID: <?= $user->getId() ?>   </p>
    <div style="display: flex;">
        <div style="flex: 50%;">
            <form action="/user/logout">
                <div class="form-group">
                    <button class="exit-button" type="submit" value="Выйти"> Выйти</button>
                </div>
            </form>
        </div>
        <div>
            <form action="/user/change">
                <div class="form-group">
                    <button class="change-button" type="submit" value="Сменить пароль"> Сменить пароль</button>
                </div>
            </form>
            <br>
        </div>
    </div>
</div>

<script>
    document.querySelector("#ava").addEventListener("change", function () {
        if (this.files[0]) {
            var fr = new FileReader();

            fr.addEventListener("load", function () {
                let form = document.querySelector('.avatar-form');
                form.submit();
            }, false);

            fr.readAsDataURL(this.files[0]);
        }
    });
</script>