<div class="card">
    <form action="/blog/sendMessage/" enctype="multipart/form-data" method="post">
        <h4>Сообщение:</h4>
        <textarea name="text" style="width: 100%; height: 100px;" required=></textarea><br><br>
        <label for="userfile"><i class="fa fa-clipboard" aria-hidden="true"></i><span id="file_name" style="margin-left: 10px;">Прикрепить картинку</span></label>
        <input type="file" id="userfile" name="userfile"  accept=".jpg, .jpeg, .png" hidden/><br />
        <div class="form-group">
            <button class="send-message" type="submit" value="Выйти">Отправить</button>
        </div>
        <br><br>
    </form>
</div>


<script>
    document.querySelector("#userfile").addEventListener("change", function () {
        if (this.files[0]) {
            console.log(this.files[0]);
            if (this.files[0].size > 3000000) {
                alert("Файл слишком большой и не будет загружен.");
                document.getElementById('userfile').value = null;
            } else
                document.querySelector("#file_name").innerText = this.files[0].name;
        }
    });
</script>