<div class="card">
    <form action="/blog/sendMessage/" enctype="multipart/form-data" method="post">
        <h4>Сообщение:</h4>
        <textarea name="text" style="width: 100%; height: 100px;" required=></textarea><br>
        <h5>Прикрепить картинку:</h5>
        <input name="userfile" type="file" /><br><br>
        <div class="form-group">
            <button class="send-message" type="submit" value="Выйти">Отправить</button>
        </div>
        <br><br>
    </form>
</div>