<div class="card">
    <h4>Сообщение # <?= $message->getId() ?>
        <?php if ($user->isAdmin()): ?>
            <a href="/blog/deletemessage/?id=<?= $message->getId() ?>">
                <div class="remove">
                    <img src="https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcS4VbaLGoKcbJZuAMbe7t1Gixa0oqurMd07xiiL453GDB3kGVsa5C_4MQ" width="20" height="20"/>Удалить
                </div>
            </a>
        <?php endif; ?>
    </h4>
    <?php if ($message->getImage()): ?>
        <div class="blogimg">
            <img src="/blog/getimage/?id=<?= $message->getImage() ?>"></img>
        </div>
    <?php endif; ?>
    <p><?= $message->getText(); ?></p>
    <h5><b><?= $message->getUser()->getName() ?></b>, <?= $message->getCreatedAt() ?></h5>
</div>