<head>
    <link rel="stylesheet" type="text/css" href="/html/css/blog.css">
    <meta charset="UTF-8">
    <title></title>
</head>
<div class="header">
    <h2>Blog Name</h2>
</div>

<div class="row">
    <div class="leftcolumn">
        <?php
        foreach ($messages as $message) {
            include('_message.phtml');
        }
        ?>

    </div>
    <div class="rightcolumn">
        <?php include('_form.phtml'); ?>
        <?php include('_about.phtml'); ?>
        <?php include('_popular.phtml'); ?>
        <?php include('_follow.phtml'); ?>
    </div>
</div>

<br>
<br>

<div class="footer">
    <h2>Footer</h2>
</div>


<style>

</style>
