Регистрация:<br>
<form action="/user/register" method="post" name="reg_form" onsubmit="return validateForm()" >
    Имя: <input type="text" name="name" value="<?= $name ?? "" ?>" required> <br><br>
    Email: <input type="text" name="email" value="<?= $email ?? "" ?>" required> <br><br>
    Пароль: <input type="password" name="password" required> <br><br>
    Повторите Пароль: <input type="password" name="password_" required> <br><br>
    <input type="submit" value="Зарегистрироваться">
</form>
<br>
<br>

Войти
<form action="/user/login" method="post">
    Email: <input type="text" name="email" required> <br><br>
    Пароль: <input type="password" name="password" required> <br><br>
    <input type="submit" value="Войти">
</form>

<br>
<br>
<?php if ($this->error): ?>
    <span style="color: red"><?= $this->error; ?></span>
<?php endif; ?>

<script>
    function validateForm() {
        var pass = document.forms["reg_form"]["password"].value;
        var pass_ = document.forms["reg_form"]["password_"].value;
        if (pass !== pass_) {
            alert("Пароли не совпадают");
            return false;
        }
    }
</script>>