<!DOCTYPE html>
<html>
    <head>
        <link rel="stylesheet" type="text/css" href="/html/css/admin.css">
        <link rel="stylesheet" type="text/css" href="/html/css/font-awesome.min.css">
        <meta charset="UTF-8">
        <title></title>
    </head>
    <body>
        <div class="container">
            <div style="display: flex;">
                <div style="flex: 50%;">
                    <form class="contact_form">
                        <button class="add_user"  formaction="/admin/add/">Добавить</button>
                    </form>
                    <!--<h2>Админ панель. Пользователь: <?= $admin['name']; ?></h2>-->
                </div>
                <div>
                    <h2><a href="/blog"> В Блог</a></h2>
                </div>
            </div>
            <table class="table">
                <thead>
                <th align="center">ID</th>
                <th align="center">Имя</th>
                <th align="center">Email</th>
                <th align="center">Админ</th>
                <th align="center">Действия</th>

                </thead>
                <?php foreach ($users as $user): ?>
                    <tr>
                        <td><?= $user['id'] ?></td>
                        <td><?= $user['name'] ?></td>
                        <td><?= $user['email'] ?></td>
                        <td><?= ($user['is_admin'] == 1) ? "Да" : "Нет" ?></td>
                        <td class="actionbar">
                            <ul class="actionbar">
                                <li><a href="/admin/edit/<?php echo $user['id'] ?>" title="Редактировать"><i class="fa fa-pencil-square-o"></i></a></li>
                                <li><a href="/admin/delete/<?php echo $user['id'] ?>" title="Редактировать"><i class="fa fa-times"></i></a></li>
                                <li><a href="/admin/signin/<?php echo $user['id'] ?>" title="Авторизоваться"><i class="fa fa-sign-in"></i></a></li>
                            </ul>
                        </td>
                    </tr>
                <?php endforeach; ?>
            </table>

        </div>
    </body>
</html>
